# Generated by Django 2.2 on 2020-06-03 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist', '0001_initial'),
        ('gaana', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('playlistsongid', models.AutoField(primary_key=True, serialize=False)),
                ('playlistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist')),
                ('songid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaana.Music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
