# Generated by Django 2.2 on 2020-06-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='user',
        ),
    ]
