# Generated by Django 2.2 on 2020-06-08 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gaana', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('RecentlyPlayedid', models.AutoField(primary_key=True, serialize=False)),
                ('songid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaana.Music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recentlyplayed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
