# Generated by Django 2.2 on 2020-06-08 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recently_played', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyplayed',
            name='published_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
