# Generated by Django 2.2 on 2020-05-15 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('musicid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='music/')),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
