# Generated by Django 2.2 on 2020-06-11 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('musicid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='music/')),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('serialid', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='album.Album')),
            ],
        ),
    ]
