# Generated by Django 2.2 on 2020-06-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0004_recprofile_user_pca_obj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecProfile',
        ),
    ]
